-- Additional Jobs for Existing Organizations

INSERT INTO jobs (
    title,
    description,
    organization_id,
    requirements,
    skills,
    status,
    location,
    job_type,
    salary_min,
    salary_max,
    salary_currency,
    remote,
    is_mock,
    created_at,
    updated_at
) VALUES
-- Oak Tech - Mobile Developer
(
    '{"en": "Senior Mobile Developer", "fr": "Développeur Mobile Senior"}'::jsonb,
    '{"en": "Join our mobile team to build cross-platform applications using React Native and modern mobile development practices.", "fr": "Rejoignez notre équipe mobile pour développer des applications multiplateformes avec React Native et les pratiques modernes de développement mobile."}'::jsonb,
    '4357d073-2490-4aaf-af7e-f781206cde96',
    '{"en": ["5+ years of mobile development experience", "Strong expertise in React Native", "Experience with native modules", "Knowledge of iOS and Android platforms"], "fr": ["5+ ans d''expérience en développement mobile", "Forte expertise en React Native", "Expérience avec les modules natifs", "Connaissance des plateformes iOS et Android"]}'::jsonb,
    ARRAY['REACT_NATIVE', 'TYPESCRIPT', 'IOS', 'ANDROID'],
    'PUBLISHED',
    '{"city": {"en": "San Francisco", "fr": "San Francisco"}, "state": {"en": "California", "fr": "Californie"}, "country": {"en": "United States", "fr": "États-Unis"}, "postal_code": {"en": "94105", "fr": "94105"}}'::jsonb,
    'FULL_TIME',
    130000,
    190000,
    'USD',
    true,
    true,
    NOW(),
    NOW()
),
-- Tech Sim - Security Engineer
(
    '{"en": "Senior Security Engineer", "fr": "Ingénieur Sécurité Senior"}'::jsonb,
    '{"en": "Lead security initiatives and implement best practices for cloud infrastructure and application security.", "fr": "Diriger les initiatives de sécurité et mettre en œuvre les meilleures pratiques pour la sécurité des infrastructures cloud et des applications."}'::jsonb,
    '8b809740-9391-4add-be1e-d76db1851e39',
    '{"en": ["7+ years in security engineering", "Experience with cloud security", "Knowledge of compliance frameworks", "Incident response experience"], "fr": ["7+ ans en ingénierie de sécurité", "Expérience en sécurité cloud", "Connaissance des cadres de conformité", "Expérience en réponse aux incidents"]}'::jsonb,
    ARRAY['SECURITY', 'AWS_SECURITY', 'COMPLIANCE', 'PENETRATION_TESTING'],
    'PUBLISHED',
    '{"city": {"en": "Austin", "fr": "Austin"}, "state": {"en": "Texas", "fr": "Texas"}, "country": {"en": "United States", "fr": "États-Unis"}, "postal_code": {"en": "78701", "fr": "78701"}}'::jsonb,
    'FULL_TIME',
    150000,
    200000,
    'USD',
    true,
    true,
    NOW(),
    NOW()
),
-- Lion BI - Machine Learning Engineer
(
    '{"en": "Senior Machine Learning Engineer", "fr": "Ingénieur Machine Learning Senior"}'::jsonb,
    '{"en": "Design and implement machine learning models for our predictive analytics platform.", "fr": "Concevoir et implémenter des modèles de machine learning pour notre plateforme d''analyse prédictive."}'::jsonb,
    '917fda56-09ed-44ac-a798-fd50a61a2396',
    '{"en": ["Masters/PhD in ML, Computer Science or related", "Experience with deep learning frameworks", "Production ML deployment experience", "Strong mathematical background"], "fr": ["Master/Doctorat en ML, Informatique ou domaine connexe", "Expérience avec les frameworks de deep learning", "Expérience en déploiement ML en production", "Solide formation mathématique"]}'::jsonb,
    ARRAY['PYTORCH', 'TENSORFLOW', 'MLOPS', 'DEEP_LEARNING'],
    'PUBLISHED',
    '{"city": {"en": "Boston", "fr": "Boston"}, "state": {"en": "Massachusetts", "fr": "Massachusetts"}, "country": {"en": "United States", "fr": "États-Unis"}, "postal_code": {"en": "02108", "fr": "02108"}}'::jsonb,
    'FULL_TIME',
    160000,
    220000,
    'USD',
    true,
    true,
    NOW(),
    NOW()
),
-- Mat Tech - DevOps Lead
(
    '{"en": "DevOps Team Lead", "fr": "Chef d''équipe DevOps"}'::jsonb,
    '{"en": "Lead our DevOps team in implementing and maintaining our cloud infrastructure and deployment pipelines.", "fr": "Diriger notre équipe DevOps dans la mise en œuvre et la maintenance de notre infrastructure cloud et de nos pipelines de déploiement."}'::jsonb,
    'b4921f4b-8f67-439d-8e30-c4364dfe2f17',
    '{"en": ["8+ years of DevOps experience", "Team leadership experience", "Strong AWS expertise", "Experience with microservices"], "fr": ["8+ ans d''expérience en DevOps", "Expérience en leadership d''équipe", "Forte expertise AWS", "Expérience avec les microservices"]}'::jsonb,
    ARRAY['AWS', 'KUBERNETES', 'TERRAFORM', 'TEAM_LEADERSHIP'],
    'PUBLISHED',
    '{"city": {"en": "Seattle", "fr": "Seattle"}, "state": {"en": "Washington", "fr": "Washington"}, "country": {"en": "United States", "fr": "États-Unis"}, "postal_code": {"en": "98101", "fr": "98101"}}'::jsonb,
    'FULL_TIME',
    170000,
    230000,
    'USD',
    true,
    true,
    NOW(),
    NOW()
),
-- Auchan - Digital Marketing Specialist
(
    '{"en": "Digital Marketing Specialist", "fr": "Spécialiste Marketing Digital"}'::jsonb,
    '{"en": "Drive digital marketing initiatives and social media presence for our retail operations.", "fr": "Piloter les initiatives de marketing digital et la présence sur les réseaux sociaux pour nos opérations de vente au détail."}'::jsonb,
    '71f38f4e-b172-43f2-83d2-aa8463d9a0c3',
    '{"en": ["3+ years in digital marketing", "Social media management experience", "Experience with marketing analytics", "Content creation skills"], "fr": ["3+ ans en marketing digital", "Expérience en gestion des réseaux sociaux", "Expérience en analyse marketing", "Compétences en création de contenu"]}'::jsonb,
    ARRAY['DIGITAL_MARKETING', 'SOCIAL_MEDIA', 'ANALYTICS', 'CONTENT_CREATION'],
    'PUBLISHED',
    '{"city": {"en": "Chicago", "fr": "Chicago"}, "state": {"en": "Illinois", "fr": "Illinois"}, "country": {"en": "United States", "fr": "États-Unis"}, "postal_code": {"en": "60601", "fr": "60601"}}'::jsonb,
    'FULL_TIME',
    65000,
    85000,
    'USD',
    false,
    true,
    NOW(),
    NOW()
),
-- Oak Tech - Product Manager
(
    '{"en": "Senior Product Manager", "fr": "Chef de Produit Senior"}'::jsonb,
    '{"en": "Lead product strategy and development for our enterprise SaaS platform.", "fr": "Diriger la stratégie et le développement produit pour notre plateforme SaaS entreprise."}'::jsonb,
    '4357d073-2490-4aaf-af7e-f781206cde96',
    '{"en": ["5+ years in product management", "Experience with B2B SaaS products", "Strong analytical skills", "Technical background preferred"], "fr": ["5+ ans en gestion de produit", "Expérience avec les produits SaaS B2B", "Fortes compétences analytiques", "Formation technique préférée"]}'::jsonb,
    ARRAY['PRODUCT_MANAGEMENT', 'AGILE', 'DATA_ANALYSIS', 'SAAS'],
    'PUBLISHED',
    '{"city": {"en": "San Francisco", "fr": "San Francisco"}, "state": {"en": "California", "fr": "Californie"}, "country": {"en": "United States", "fr": "États-Unis"}, "postal_code": {"en": "94105", "fr": "94105"}}'::jsonb,
    'FULL_TIME',
    140000,
    200000,
    'USD',
    true,
    true,
    NOW(),
    NOW()
),
-- Tech Sim - Site Reliability Engineer
(
    '{"en": "Site Reliability Engineer", "fr": "Ingénieur en Fiabilité de Site"}'::jsonb,
    '{"en": "Ensure reliability and performance of our cloud infrastructure and services.", "fr": "Assurer la fiabilité et la performance de notre infrastructure cloud et de nos services."}'::jsonb,
    '8b809740-9391-4add-be1e-d76db1851e39',
    '{"en": ["5+ years of SRE experience", "Strong Linux systems knowledge", "Experience with monitoring tools", "On-call rotation experience"], "fr": ["5+ ans d''expérience en SRE", "Solide connaissance des systèmes Linux", "Expérience avec les outils de monitoring", "Expérience en rotation d''astreinte"]}'::jsonb,
    ARRAY['SRE', 'LINUX', 'PROMETHEUS', 'GRAFANA'],
    'PUBLISHED',
    '{"city": {"en": "Austin", "fr": "Austin"}, "state": {"en": "Texas", "fr": "Texas"}, "country": {"en": "United States", "fr": "États-Unis"}, "postal_code": {"en": "78701", "fr": "78701"}}'::jsonb,
    'FULL_TIME',
    140000,
    190000,
    'USD',
    true,
    true,
    NOW(),
    NOW()
),
-- Lion BI - Data Engineer
(
    '{"en": "Senior Data Engineer", "fr": "Ingénieur Data Senior"}'::jsonb,
    '{"en": "Design and implement data pipelines and infrastructure for our analytics platform.", "fr": "Concevoir et mettre en œuvre des pipelines de données et l''infrastructure pour notre plateforme d''analyse."}'::jsonb,
    '917fda56-09ed-44ac-a798-fd50a61a2396',
    '{"en": ["6+ years of data engineering experience", "Experience with big data technologies", "Strong SQL and Python skills", "ETL pipeline experience"], "fr": ["6+ ans d''expérience en ingénierie des données", "Expérience avec les technologies big data", "Solides compétences en SQL et Python", "Expérience en pipeline ETL"]}'::jsonb,
    ARRAY['APACHE_SPARK', 'AIRFLOW', 'PYTHON', 'SQL'],
    'PUBLISHED',
    '{"city": {"en": "New York", "fr": "New York"}, "state": {"en": "New York", "fr": "New York"}, "country": {"en": "United States", "fr": "États-Unis"}, "postal_code": {"en": "10001", "fr": "10001"}}'::jsonb,
    'FULL_TIME',
    140000,
    190000,
    'USD',
    true,
    true,
    NOW(),
    NOW()
),
-- Mat Tech - QA Automation Engineer
(
    '{"en": "QA Automation Engineer", "fr": "Ingénieur QA Automation"}'::jsonb,
    '{"en": "Develop and maintain automated test frameworks for our backend services.", "fr": "Développer et maintenir des frameworks de test automatisé pour nos services backend."}'::jsonb,
    'b4921f4b-8f67-439d-8e30-c4364dfe2f17',
    '{"en": ["4+ years in test automation", "Experience with API testing", "CI/CD pipeline experience", "Programming skills in Python or Java"], "fr": ["4+ ans en automatisation de tests", "Expérience en test d''API", "Expérience en pipeline CI/CD", "Compétences en programmation Python ou Java"]}'::jsonb,
    ARRAY['SELENIUM', 'PYTEST', 'API_TESTING', 'CI_CD'],
    'PUBLISHED',
    '{"city": {"en": "Seattle", "fr": "Seattle"}, "state": {"en": "Washington", "fr": "Washington"}, "country": {"en": "United States", "fr": "États-Unis"}, "postal_code": {"en": "98101", "fr": "98101"}}'::jsonb,
    'FULL_TIME',
    110000,
    160000,
    'USD',
    true,
    true,
    NOW(),
    NOW()
),
-- Auchan - Supply Chain Analyst
(
    '{"en": "Supply Chain Analyst", "fr": "Analyste Chaîne d''Approvisionnement"}'::jsonb,
    '{"en": "Analyze and optimize supply chain operations for our retail network.", "fr": "Analyser et optimiser les opérations de la chaîne d''approvisionnement pour notre réseau de vente au détail."}'::jsonb,
    '71f38f4e-b172-43f2-83d2-aa8463d9a0c3',
    '{"en": ["3+ years in supply chain analytics", "Experience with ERP systems", "Strong Excel and SQL skills", "Knowledge of logistics operations"], "fr": ["3+ ans en analyse de chaîne d''approvisionnement", "Expérience avec les systèmes ERP", "Solides compétences en Excel et SQL", "Connaissance des opérations logistiques"]}'::jsonb,
    ARRAY['SUPPLY_CHAIN', 'ERP', 'SQL', 'DATA_ANALYSIS'],
    'PUBLISHED',
    '{"city": {"en": "Chicago", "fr": "Chicago"}, "state": {"en": "Illinois", "fr": "Illinois"}, "country": {"en": "United States", "fr": "États-Unis"}, "postal_code": {"en": "60601", "fr": "60601"}}'::jsonb,
    'FULL_TIME',
    70000,
    95000,
    'USD',
    false,
    true,
    NOW(),
    NOW()
); 